---

# MySql Server 5.6 (not 5.5 or 5.7 !!)
- name: "Ensure MySQL Server 5.6 is installed."
  yum: name=mysql56-server state=present
  become: true
- name: "Ensure MySQL Server is running."
  service: name=mysqld state=started
  become: true
- name: "Ensure MySQL Server is starting on bootup."
  service: name=mysqld enabled=yes
  become: true

# Create MySQL user
- name: "Ensure python mysql dependencies are installed."
  yum: pkg={{ item }} state=present
  become: true
  with_items:
    - mysql-devel
    - python-devel
    - python-setuptools
- name: "Ensure Python-MySqlDb package is installed."
  pip: name=MySQL-python
  become: true
